name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL : "postgres://localhost:5321" # dummy URL to generate client
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: cd integration-test-bun && bun install

      - name: Generate Prisma Client
        run: cd integration-test-bun && bunx prisma generate

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Docker Compose 
        uses: docker/setup-qemu-action@v2

      - name: Ensure docker compose is available
        run: docker compose version

      - name: Copy .env.example to .env 
        run: cp ./integration-test-bun/.env.example ./integration-test-bun/.env 

      - name: Run integration script 
        run: cd integration-test-bun && bun run test:integration

